services:
  polla-backend:
    build: ./backend
    container_name: polla-backend
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:4010:4010"
    volumes:
      - ./data:/data
    restart: always
