import type { Artist, PricePoint } from './types.js';

const nowSeconds = Math.floor(Date.now() / 1000);

function history(base: number, drift: number, phase: number): PricePoint[] {
  return Array.from({ length: 72 }, (_, index) => {
    const time = nowSeconds - (71 - index) * 60 * 60;
    const wave = Math.sin((index + phase) / 6) * 2.1;
    const trend = index * drift;
    return { time, value: Number((base + trend + wave).toFixed(2)) };
  });
}

interface ArtistSeed {
  id: string;
  slug: string;
  symbol: string;
  name: string;
  country: string;
  genre: string;
  category: string;
  subcategory: string;
  profession: string;
  themeTags: string[];
  volatilityProfile: Artist['volatilityProfile'];
  riskLevel: number;
  strategyNotes: string;
  currentPrice: number;
  openingPrice: number;
  liquidity: number;
  holders: number;
}

const seeds: ArtistSeed[] = [
  {
    id: 'artist-karol-g',
    slug: 'karol-g',
    symbol: 'KAROL',
    name: 'Karol G',
    country: 'Colombia',
    genre: 'Urbano latino',
    category: 'musica',
    subcategory: 'urbano-latino',
    profession: 'Artista musical',
    themeTags: ['musica', 'latino', 'colombia', 'urbano'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Figura de alta demanda con actividad frecuente y liquidez media.',
    currentPrice: 118.42,
    openingPrice: 112.6,
    liquidity: 2200,
    holders: 824
  },
  {
    id: 'artist-bad-bunny',
    slug: 'bad-bunny',
    symbol: 'BENITO',
    name: 'Bad Bunny',
    country: 'Puerto Rico',
    genre: 'Trap latino',
    category: 'musica',
    subcategory: 'trap-latino',
    profession: 'Cantante y compositor',
    themeTags: ['musica', 'latino', 'puerto-rico', 'trap'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes:
      'Figura muy seguida; puede moverse fuerte con lanzamientos, tendencias o noticias verificadas.',
    currentPrice: 104.75,
    openingPrice: 106.2,
    liquidity: 2600,
    holders: 1018
  },
  {
    id: 'artist-shakira',
    slug: 'shakira',
    symbol: 'SHAKI',
    name: 'Shakira',
    country: 'Colombia',
    genre: 'Pop latino',
    category: 'musica',
    subcategory: 'pop-latino',
    profession: 'Artista musical',
    themeTags: ['musica', 'latino', 'colombia', 'pop'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes:
      'Figura consolidada con base amplia; perfil mas defensivo dentro del mercado ficticio.',
    currentPrice: 127.18,
    openingPrice: 119.9,
    liquidity: 2400,
    holders: 936
  },
  {
    id: 'artist-feid',
    slug: 'feid',
    symbol: 'FEID',
    name: 'Feid',
    country: 'Colombia',
    genre: 'Urbano latino',
    category: 'musica',
    subcategory: 'urbano-latino',
    profession: 'Artista musical',
    themeTags: ['musica', 'latino', 'colombia', 'urbano'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes:
      'Perfil de crecimiento rapido; sensible a lanzamientos, giras y tendencias sociales.',
    currentPrice: 86.4,
    openingPrice: 83.8,
    liquidity: 1850,
    holders: 512
  },
  {
    id: 'artist-j-balvin',
    slug: 'j-balvin',
    symbol: 'JBALV',
    name: 'J Balvin',
    country: 'Colombia',
    genre: 'Urbano latino',
    category: 'musica',
    subcategory: 'urbano-latino',
    profession: 'Artista musical',
    themeTags: ['musica', 'latino', 'colombia', 'urbano'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Marca global latina con movimientos moderados y buen reconocimiento.',
    currentPrice: 93.15,
    openingPrice: 91.5,
    liquidity: 1950,
    holders: 548
  },
  {
    id: 'artist-rauw-alejandro',
    slug: 'rauw-alejandro',
    symbol: 'RAUW',
    name: 'Rauw Alejandro',
    country: 'Puerto Rico',
    genre: 'Urbano latino',
    category: 'musica',
    subcategory: 'urbano-latino',
    profession: 'Artista musical',
    themeTags: ['musica', 'latino', 'puerto-rico', 'urbano'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Alta sensibilidad a colaboraciones, giras y lanzamientos recientes.',
    currentPrice: 88.75,
    openingPrice: 87.3,
    liquidity: 1800,
    holders: 493
  },
  {
    id: 'artist-peso-pluma',
    slug: 'peso-pluma',
    symbol: 'PPLUMA',
    name: 'Peso Pluma',
    country: 'Mexico',
    genre: 'Regional mexicano',
    category: 'musica',
    subcategory: 'regional-mexicano',
    profession: 'Artista musical',
    themeTags: ['musica', 'mexico', 'regional', 'corridos'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Figura de alta volatilidad por ciclos virales y colaboraciones.',
    currentPrice: 91.8,
    openingPrice: 89.2,
    liquidity: 1900,
    holders: 577
  },
  {
    id: 'artist-anitta',
    slug: 'anitta',
    symbol: 'ANITA',
    name: 'Anitta',
    country: 'Brasil',
    genre: 'Pop/funk',
    category: 'musica',
    subcategory: 'pop-global',
    profession: 'Artista musical',
    themeTags: ['musica', 'brasil', 'pop', 'global'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Figura internacional con actividad multilingue y presencia de marca.',
    currentPrice: 84.6,
    openingPrice: 82.9,
    liquidity: 1700,
    holders: 421
  },
  {
    id: 'artist-dua-lipa',
    slug: 'dua-lipa',
    symbol: 'DUA',
    name: 'Dua Lipa',
    country: 'Reino Unido',
    genre: 'Pop',
    category: 'musica',
    subcategory: 'pop-global',
    profession: 'Artista musical',
    themeTags: ['musica', 'global', 'pop'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes: 'Perfil global relativamente estable con picos por lanzamientos y giras.',
    currentPrice: 121.25,
    openingPrice: 118.4,
    liquidity: 2500,
    holders: 744
  },
  {
    id: 'artist-taylor-swift',
    slug: 'taylor-swift',
    symbol: 'TSWFT',
    name: 'Taylor Swift',
    country: 'Estados Unidos',
    genre: 'Pop',
    category: 'musica',
    subcategory: 'pop-global',
    profession: 'Artista musical',
    themeTags: ['musica', 'global', 'pop', 'usa'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes:
      'Figura de escala masiva; movimientos defensivos con picos por eventos mayores.',
    currentPrice: 138.9,
    openingPrice: 135.2,
    liquidity: 3200,
    holders: 1210
  },
  {
    id: 'artist-drake',
    slug: 'drake',
    symbol: 'DRAKE',
    name: 'Drake',
    country: 'Canada',
    genre: 'Hip hop',
    category: 'musica',
    subcategory: 'hip-hop',
    profession: 'Artista musical',
    themeTags: ['musica', 'global', 'hip-hop', 'canada'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes:
      'Activo global con sensibilidad a lanzamientos, colaboraciones y debates publicos.',
    currentPrice: 116.1,
    openingPrice: 115,
    liquidity: 2600,
    holders: 792
  },
  {
    id: 'artist-mrbeast',
    slug: 'mrbeast',
    symbol: 'MRBST',
    name: 'MrBeast',
    country: 'Estados Unidos',
    genre: 'Video digital',
    category: 'creadores',
    subcategory: 'youtube-global',
    profession: 'Creador de contenido',
    themeTags: ['creadores', 'youtube', 'global', 'retos'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Creador con picos fuertes por publicaciones virales y proyectos grandes.',
    currentPrice: 132.4,
    openingPrice: 128.8,
    liquidity: 3000,
    holders: 1104
  },
  {
    id: 'artist-ibai-llanos',
    slug: 'ibai-llanos',
    symbol: 'IBAI',
    name: 'Ibai Llanos',
    country: 'Espana',
    genre: 'Streaming',
    category: 'creadores',
    subcategory: 'streaming',
    profession: 'Creador y presentador',
    themeTags: ['creadores', 'streaming', 'espana', 'eventos'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Creador fuerte en eventos; puede moverse por directos y colaboraciones.',
    currentPrice: 97.35,
    openingPrice: 94.8,
    liquidity: 2100,
    holders: 644
  },
  {
    id: 'artist-auronplay',
    slug: 'auronplay',
    symbol: 'AURON',
    name: 'AuronPlay',
    country: 'Espana',
    genre: 'Streaming',
    category: 'creadores',
    subcategory: 'streaming',
    profession: 'Creador de contenido',
    themeTags: ['creadores', 'streaming', 'espana'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Base amplia con movimientos moderados segun actividad y conversacion.',
    currentPrice: 89.9,
    openingPrice: 88.4,
    liquidity: 1850,
    holders: 533
  },
  {
    id: 'artist-thegrefg',
    slug: 'thegrefg',
    symbol: 'GREFG',
    name: 'TheGrefg',
    country: 'Espana',
    genre: 'Gaming',
    category: 'creadores',
    subcategory: 'gaming',
    profession: 'Creador de contenido',
    themeTags: ['creadores', 'gaming', 'espana', 'streaming'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Perfil sensible a eventos de gaming, directos y colaboraciones.',
    currentPrice: 80.7,
    openingPrice: 79.1,
    liquidity: 1600,
    holders: 402
  },
  {
    id: 'artist-luisito-comunica',
    slug: 'luisito-comunica',
    symbol: 'LUISITO',
    name: 'Luisito Comunica',
    country: 'Mexico',
    genre: 'Video digital',
    category: 'creadores',
    subcategory: 'viajes',
    profession: 'Creador de contenido',
    themeTags: ['creadores', 'youtube', 'mexico', 'viajes'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Creador latino con actividad internacional y audiencia diversificada.',
    currentPrice: 82.85,
    openingPrice: 81.3,
    liquidity: 1700,
    holders: 469
  },
  {
    id: 'artist-el-rubius',
    slug: 'el-rubius',
    symbol: 'RUBIUS',
    name: 'El Rubius',
    country: 'Espana',
    genre: 'Gaming',
    category: 'creadores',
    subcategory: 'gaming',
    profession: 'Creador de contenido',
    themeTags: ['creadores', 'gaming', 'espana', 'youtube'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes: 'Creador historico con base defensiva y menor volatilidad diaria.',
    currentPrice: 86.1,
    openingPrice: 85.5,
    liquidity: 1750,
    holders: 488
  },
  {
    id: 'artist-zendaya',
    slug: 'zendaya',
    symbol: 'ZNDYA',
    name: 'Zendaya',
    country: 'Estados Unidos',
    genre: 'Cine y television',
    category: 'cine-tv',
    subcategory: 'actuacion',
    profession: 'Actriz',
    themeTags: ['cine-tv', 'global', 'actuacion', 'moda'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Figura global con picos por estrenos, alfombras rojas y campanas.',
    currentPrice: 119.8,
    openingPrice: 117.7,
    liquidity: 2450,
    holders: 775
  },
  {
    id: 'artist-pedro-pascal',
    slug: 'pedro-pascal',
    symbol: 'PEDRO',
    name: 'Pedro Pascal',
    country: 'Chile/Estados Unidos',
    genre: 'Cine y television',
    category: 'cine-tv',
    subcategory: 'actuacion',
    profession: 'Actor',
    themeTags: ['cine-tv', 'global', 'actuacion', 'latam'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Actor con alta conversacion por estrenos y franquicias.',
    currentPrice: 111.45,
    openingPrice: 108.2,
    liquidity: 2300,
    holders: 714
  },
  {
    id: 'artist-jenna-ortega',
    slug: 'jenna-ortega',
    symbol: 'JENNA',
    name: 'Jenna Ortega',
    country: 'Estados Unidos',
    genre: 'Cine y television',
    category: 'cine-tv',
    subcategory: 'actuacion',
    profession: 'Actriz',
    themeTags: ['cine-tv', 'global', 'actuacion'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Perfil joven con picos fuertes por estrenos, trailers y fandom.',
    currentPrice: 99.25,
    openingPrice: 96.1,
    liquidity: 2050,
    holders: 631
  },
  {
    id: 'artist-salma-hayek',
    slug: 'salma-hayek',
    symbol: 'SALMA',
    name: 'Salma Hayek',
    country: 'Mexico',
    genre: 'Cine',
    category: 'cine-tv',
    subcategory: 'actuacion',
    profession: 'Actriz y productora',
    themeTags: ['cine-tv', 'mexico', 'actuacion'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes:
      'Figura consolidada con comportamiento mas defensivo y picos por apariciones.',
    currentPrice: 78.4,
    openingPrice: 77.6,
    liquidity: 1500,
    holders: 357
  },
  {
    id: 'artist-dwayne-johnson',
    slug: 'dwayne-johnson',
    symbol: 'ROCK',
    name: 'Dwayne Johnson',
    country: 'Estados Unidos',
    genre: 'Cine',
    category: 'cine-tv',
    subcategory: 'actuacion',
    profession: 'Actor',
    themeTags: ['cine-tv', 'global', 'accion', 'fitness'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes: 'Marca personal fuerte con movimientos por cine, deporte y negocios.',
    currentPrice: 113.65,
    openingPrice: 112.2,
    liquidity: 2400,
    holders: 733
  },
  {
    id: 'artist-selena-gomez',
    slug: 'selena-gomez',
    symbol: 'SELENA',
    name: 'Selena Gomez',
    country: 'Estados Unidos',
    genre: 'Musica y television',
    category: 'cine-tv',
    subcategory: 'musica-actuacion',
    profession: 'Artista y actriz',
    themeTags: ['cine-tv', 'musica', 'global', 'pop'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes:
      'Figura transversal con demanda sostenida en musica, television y marca personal.',
    currentPrice: 109.2,
    openingPrice: 106.9,
    liquidity: 2250,
    holders: 704
  },
  {
    id: 'artist-lionel-messi',
    slug: 'lionel-messi',
    symbol: 'MESSI',
    name: 'Lionel Messi',
    country: 'Argentina',
    genre: 'Futbol',
    category: 'deportes',
    subcategory: 'futbol',
    profession: 'Futbolista',
    themeTags: ['deportes', 'futbol', 'argentina', 'global'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes: 'Leyenda estable; picos por partidos, records y noticias verificadas.',
    currentPrice: 141.3,
    openingPrice: 139,
    liquidity: 3400,
    holders: 1308
  },
  {
    id: 'artist-cristiano-ronaldo',
    slug: 'cristiano-ronaldo',
    symbol: 'CR7',
    name: 'Cristiano Ronaldo',
    country: 'Portugal',
    genre: 'Futbol',
    category: 'deportes',
    subcategory: 'futbol',
    profession: 'Futbolista',
    themeTags: ['deportes', 'futbol', 'portugal', 'global'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes: 'Figura global con base defensiva y picos por goles o records.',
    currentPrice: 137.75,
    openingPrice: 136.2,
    liquidity: 3350,
    holders: 1282
  },
  {
    id: 'artist-neymar',
    slug: 'neymar',
    symbol: 'NEY',
    name: 'Neymar',
    country: 'Brasil',
    genre: 'Futbol',
    category: 'deportes',
    subcategory: 'futbol',
    profession: 'Futbolista',
    themeTags: ['deportes', 'futbol', 'brasil', 'global'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Alta volatilidad por lesiones, fichajes, partidos y actividad social.',
    currentPrice: 102.55,
    openingPrice: 101.2,
    liquidity: 2150,
    holders: 668
  },
  {
    id: 'artist-lebron-james',
    slug: 'lebron-james',
    symbol: 'LBRON',
    name: 'LeBron James',
    country: 'Estados Unidos',
    genre: 'Baloncesto',
    category: 'deportes',
    subcategory: 'baloncesto',
    profession: 'Baloncestista',
    themeTags: ['deportes', 'nba', 'usa', 'global'],
    volatilityProfile: 'stable',
    riskLevel: 2,
    strategyNotes: 'Perfil deportivo global, estable y sensible a records o finales.',
    currentPrice: 124.5,
    openingPrice: 122.8,
    liquidity: 2750,
    holders: 829
  },
  {
    id: 'artist-carlos-alcaraz',
    slug: 'carlos-alcaraz',
    symbol: 'ALCRZ',
    name: 'Carlos Alcaraz',
    country: 'Espana',
    genre: 'Tenis',
    category: 'deportes',
    subcategory: 'tenis',
    profession: 'Tenista',
    themeTags: ['deportes', 'tenis', 'espana'],
    volatilityProfile: 'volatile',
    riskLevel: 4,
    strategyNotes: 'Perfil deportivo con movimientos por torneos, lesiones y rankings.',
    currentPrice: 95.95,
    openingPrice: 92.8,
    liquidity: 2000,
    holders: 608
  },
  {
    id: 'artist-simone-biles',
    slug: 'simone-biles',
    symbol: 'BILES',
    name: 'Simone Biles',
    country: 'Estados Unidos',
    genre: 'Gimnasia',
    category: 'deportes',
    subcategory: 'gimnasia',
    profession: 'Gimnasta',
    themeTags: ['deportes', 'gimnasia', 'usa', 'olimpicos'],
    volatilityProfile: 'balanced',
    riskLevel: 3,
    strategyNotes:
      'Figura deportiva de reconocimiento alto con picos por competencias mayores.',
    currentPrice: 90.35,
    openingPrice: 88.9,
    liquidity: 1850,
    holders: 522
  }
];

export const artists: Artist[] = seeds.map((seed, index) => ({
  id: seed.id,
  slug: seed.slug,
  symbol: seed.symbol,
  name: seed.name,
  country: seed.country,
  genre: seed.genre,
  category: seed.category,
  subcategory: seed.subcategory,
  profession: seed.profession,
  themeTags: seed.themeTags,
  volatilityProfile: seed.volatilityProfile,
  riskLevel: seed.riskLevel,
  strategyNotes: seed.strategyNotes,
  imageUrl: '',
  imageUsageStatus: 'none',
  imageAttribution: '',
  currentPrice: seed.currentPrice,
  openingPrice: seed.openingPrice,
  dailyAnchorPrice: seed.currentPrice,
  liquidity: seed.liquidity,
  version: 1,
  status: 'active',
  holders: seed.holders,
  history: history(seed.openingPrice * 0.96, (seed.currentPrice - seed.openingPrice) / 72, index),
  videos: []
}));
